---
spring:
  profiles: local
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  jms:
    queue:
      name: teste.extd.msg
      ri:
        name: teste.extd.msg.ri
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
